# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-05 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171105_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='num_kills_copy',
            field=models.IntegerField(default=0),
        ),
    ]
